server:
  port: 8888
  servlet:
    context-path: /prime
  
spring:
  rest-template:
    enable: true
  sql:
    init:
      data-locations: classpath:api/data.sql
      schema-locations: classpath:api/schema.sql
  jpa:
    defer-datasource-initialization: true

lombok:
  addLombokGeneratedAnnotation: true